"""Known-preference comparison table for both datasets from validated
seven-weight records, with explicit failure denominators and measured
method wall time, plus summaries of the retained beta diagnostic."""
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
import numpy as np
import pandas as pd

REPO=Path(__file__).resolve().parents[2]
CAMPAIGN=Path(os.environ.get('CAMPAIGN_ROOT',REPO/'results'/'campaign'))
FIGURES=Path(os.environ.get('FIGURES_ROOT',REPO/'data_figures'/'exp7'))
MEMORY_GRIDS=Path(os.environ.get('MEMORY_GRIDS_ROOT',REPO/'results'/'memory_grids'))
ROOT=Path(os.environ.get('CAMPAIGN_WEIGHTED_ROOT',CAMPAIGN/'weighted'))
OUT=Path(os.environ.get('CAMPAIGN_WEIGHTED_OUT',FIGURES/'exp7_weighted'))
DISPLAY={'ILP':r'\texttt{ILP} (exact)','PBS':r'\texttt{PBS}','PTS':r'\texttt{PTS}','PBS-noLP':r'\texttt{PBS} (no LP bound)','PTS-noLP':r'\texttt{PTS} (no LP bound)'}
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def read(name,csv,kind):
    path=ROOT/name/csv;proof=json.loads((path.parent/'reconstruction.json').read_text())
    assert proof['files'][csv]==sha(path) and proof['kind']==kind
    df=pd.read_csv(path);assert len(df)==proof['rows'];return df,path

def aggregate(df):
    rows=[]
    for method,g in df.groupby('method',sort=False):
        comparable=g[g.metric_eligible==1];returned=comparable[comparable.feasible==1];timed=g[g.method_wall_s.notna()]
        rows.append(dict(method=method,n=len(g),n_query_feasible=int(g.query_feasible.sum()),n_metric=len(comparable),n_returned_metric=len(returned),n_feasible=int(g.feasible.sum()),
                         n_no_assignment=int((g.solver_status=='no_assignment').sum()),n_solver_failure=int((g.solver_status=='solver_failure').sum()),n_solver_timeout=int((g.solver_status=='solver_timeout').sum()),n_reference_timeout=int((g.reference_status=='reference_timeout').sum()),
                         optimal_fraction=comparable.optimal.mean() if len(comparable) else np.nan,median_gap=returned.rel_gap.median() if len(returned) else np.nan,worst_gap=returned.rel_gap.max() if len(returned) else np.nan,
                         n_timed=len(timed),method_ms_median=timed.method_wall_s.median()*1000,method_ms_p90=timed.method_wall_s.quantile(.9)*1000,total_ms_median=timed.total_s.median()*1000,total_ms_p90=timed.total_s.quantile(.9)*1000))
    return pd.DataFrame(rows).set_index('method')

def main():
    OUT.mkdir(parents=True,exist_ok=True);sources={};overall={}
    for dataset in ['amazon','airbnb']:
        name=dataset+'_dfs' if (ROOT/(dataset+'_dfs')/'reconstruction.json').exists() else dataset   # archived depth-first job, or the fresh job
        df,path=read(name,'all_results.csv','weighted');sources[name]=path
        overall[dataset]=aggregate(df);overall[dataset].to_csv(OUT/f'{dataset}_weighted_summary.csv')
        by=df.groupby(['weights','method'],sort=False).apply(lambda g:aggregate(g.assign(method='x')).iloc[0],include_groups=False);by.to_csv(OUT/f'{dataset}_weighted_by_weight.csv')
    lines=[r'\begin{tabular}{lrrrr}',r'\toprule',r'& \multicolumn{2}{c}{Amazon} & \multicolumn{2}{c}{Airbnb} \\',r'\cmidrule(lr){2-3}\cmidrule(lr){4-5}',r'method & optimal & med.\ time & optimal & med.\ time \\',r'\midrule']
    for m in ['ILP','PBS','PTS']:
        cells=[DISPLAY[m]]
        for dataset in ['amazon','airbnb']:
            r=overall[dataset].loc[m];cells+=[f"${r.optimal_fraction:.3f}$",f"${r.total_ms_median:.2f}$\\,ms"]
        lines.append(' & '.join(cells)+r' \\')
    lines+=[r'\bottomrule',r'\end{tabular}']
    (OUT/'table_weighted.tex').write_text('% generated by scripts/exp7/build_weighted.py; optimal fraction over metric-eligible rows (proved scalar optimum), failed feasible searches count as not optimal; PTS is the depth-first policy; time is median fresh retrieval plus measured method wall time per invocation (method-only medians are in the summary CSVs)\n'+'\n'.join(lines)+'\n')
    ext=[r'\begin{tabular}{lrrrrrr}',r'\toprule',r'& \multicolumn{3}{c}{Amazon} & \multicolumn{3}{c}{Airbnb} \\',r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}',r'method & optimal & $n$ & med.\ time & optimal & $n$ & med.\ time \\',r'\midrule']
    for m in ['ILP','PBS','PTS','PBS-noLP','PTS-noLP']:
        cells=[DISPLAY[m]]
        for dataset in ['amazon','airbnb']:
            r=overall[dataset].loc[m];cells+=[f"${r.optimal_fraction:.3f}$",f"{int(r.n_metric)}",f"${r.total_ms_median:.2f}$\\,ms"]
        ext.append(' & '.join(cells)+r' \\')
    ext+=[r'\bottomrule',r'\end{tabular}']
    (OUT/'table_weighted_extended.tex').write_text('\n'.join(ext)+'\n')
    diag_path=ROOT/'amazon_beta_diagnostic'/'weighted.csv'
    if diag_path.exists() and (diag_path.parent/'reconstruction.json').exists():
        diag,path=read('amazon_beta_diagnostic','weighted.csv','weighted_diagnostic');sources['amazon_beta_diagnostic']=path
        summary=diag.groupby(['sweep','param','beta','method'],sort=False).agg(n=('query_id','size'),n_metric=('metric_eligible','sum'),n_success=('success','sum'),ratio_mean=('ratio','mean'),ratio_min=('ratio','min'),certified=('certified','mean'),method_ms_median=('method_wall_s',lambda s:s.median()*1000)).reset_index()
        summary.to_csv(OUT/'amazon_beta_diagnostic_summary.csv',index=False)
    code=REPO;diff=subprocess.check_output(['git','-C',str(code),'diff','--binary','HEAD'])
    manifest=dict(builder_sha256=sha(__file__),presentation='PTS is the depth-first policy: both tables read the *_dfs jobs, whose runner records traversal=depth_first on every PTS row; the UCT jobs remain only in the raw records',source_commit=subprocess.check_output(['git','-C',str(code),'rev-parse','HEAD'],text=True).strip(),dirty_diff_sha256=hashlib.sha256(diff).hexdigest(),
        sources={k:dict(path=str(p),sha256=sha(p),reconstruction_sha256=sha(p.parent/'reconstruction.json')) for k,p in sources.items()},
        optimal_denominator='rows whose exact ILP reference is proved optimal within the limit (metric_eligible); a feasible search that returns nothing counts as not optimal',
        time_definition='median fresh retrieval plus measured method wall time over attempted invocations (total_ms_median), consistent with the other tables; method-only medians are in the CSV summaries',
        generated={str(p.relative_to(OUT)):sha(p) for p in OUT.rglob('*') if p.is_file() and p.name!='manifest.json'})
    (OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
if __name__=='__main__':main()
