"""Combine the retained method measurements with validated g=4/16 memory runs."""
from pathlib import Path
import csv
import hashlib
import json
import re

import os
REPO = Path(__file__).resolve().parents[2]
FIGURES = Path(os.environ.get('FIGURES_ROOT', REPO / 'data_figures' / 'exp7'))
RUNS = Path(os.environ.get('MEMORY_GRIDS_ROOT', REPO / 'results' / 'memory_grids'))
SOURCE = FIGURES / 'exp7_memory/table_memory_methods.tex'
OUT = FIGURES / 'exp7_memory'
SETTINGS = ['e11_cat10k', 'e11_cat30k', 'e12_cat1m', 'e12_cat2m', 'airbnb_12c']
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
original=[]
for line in SOURCE.read_text().splitlines():
    values = re.findall(r'\(\+\$([0-9.]+)\$\)', line)
    if values:
        assert len(values) in (5, 6)  # the sixth column is the conventional Pareto DP (R6), added on 2026-09-18
        original.append((line.split('&',1)[0].strip(),values))
assert len(original)==len(SETTINGS)
rows=[]; data=[]; sources={str(SOURCE):sha(SOURCE)}
for setting,(catalog,old) in zip(SETTINGS,original):
    path=RUNS/setting/f'mem_{setting}.json'
    validation_path=RUNS/setting/'validation.json'
    validation=json.loads(validation_path.read_text())
    assert validation['record_sha256']==sha(path)
    assert validation['queries']==100 and validation['setting']==setting
    record=json.loads(path.read_text())
    values=[]
    for grid in [4,16]:
        child=record['search_processes'][f'eps-ILP-g{grid}']
        assert child['config']['eps_grid']==grid and child['requested']==100
        assert child['sampling_interval_s']==.001
        increase=child['sampled_search_increase_mb']
        assert abs(child['sampled_search_peak_rss_mb']-child['candidate_resident_baseline_mb']-increase)<1e-8
        values.append(f'{increase:.2f}')
        data.append(dict(setting=setting,catalog=catalog,grid=grid,n_queries=child['requested'],returned=child['returned'],timeouts=child['timeouts'],sampling_interval_s=child['sampling_interval_s'],baseline_mb=child['candidate_resident_baseline_mb'],sampled_peak_mb=child['sampled_search_peak_rss_mb'],increase_mb=increase,source=str(path),source_sha256=sha(path)))
    # The four non-ILP comparisons are carried over without rounding changes.
    cells=old[:2]+values+old[3:]  # PBS, PTS, g=4, g=16, PBS unbounded, Pareto DP, and the conventional DP when present
    assert len(cells) in (6, 7)  # seven with the conventional Pareto DP column
    if setting != 'airbnb_12c':
        rows.append(catalog+' & '+' & '.join('$'+v+r'$\,MB' for v in cells)+r' \\')
    for p in [path,validation_path]:sources[str(p)]=sha(p)
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'table_memory_increases.tex').write_text(
    '% Generated by scripts/exp7/build_memory_increase_table.py.\n'
    '% Amazon catalogs only; Airbnb measurements remain in memory_ilp_grids.csv.\n'
    '% PBS, PTS, unbounded PBS, and DP retain their original measurements.\n'
    '% Epsilon-ILP g=4 and g=16 are validated measurements from the memory grid jobs (scripts/exp4/memory_grid_jobs.json).\n'
    +'\n'.join([r'\begin{tabular}{l'+'r'*(len(original[0][1])+1)+'}',r'\toprule',
    r'Catalog & \texttt{PBS} & \texttt{PTS} & $\epsilon$-ILP ($g{=}4$) & $\epsilon$-ILP ($g{=}16$) & PBS unbounded & DP'+(r' & Pareto DP (conv.)' if len(original[0][1])==6 else '')+r' \\',
    r'\midrule',*rows,r'\bottomrule',r'\end{tabular}'])+'\n')
with (OUT/'memory_ilp_grids.csv').open('w') as f:
    writer=csv.DictWriter(f,fieldnames=list(data[0]),lineterminator='\n');writer.writeheader();writer.writerows(data)
manifest=dict(builder_sha256=sha(Path(__file__)),sources=sources,semantics='Table presents Amazon catalogs only; CSV retains both datasets. Sampled peak RSS increase over each fresh process baseline after loading the same 100 candidate inputs. Sample interval 1 ms. Non-ILP columns retain original values; ILP columns rerun sequentially with g=4 and g=16 and 60 s per-query limits.',outputs={n:sha(OUT/n) for n in ['table_memory_increases.tex','memory_ilp_grids.csv']})
(OUT/'manifest_increases.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(data,indent=2))
